export const PROSPECT_STATUSES = {
  ASSESSING: "Assessing",
  DOCUMENTS_NEEDED: "Documents needed",
  INCOMPLETE: "Incomplete"
};

export const ALLOWED_EDIT_STATUSES = [
  PROSPECT_STATUSES.ASSESSING,
  PROSPECT_STATUSES.INCOMPLETE,
  PROSPECT_STATUSES.DOCUMENTS_NEEDED
];
