export const PROSPECT_STATUSES = {
  ASSESSING: "Assessing",
  DOCUMENTS_NEEDED: "Documents needed"
};

export const STATUS_ALLOWED_EDIT = [
  PROSPECT_STATUSES.ASSESSING,
  PROSPECT_STATUSES.DOCUMENTS_NEEDED
];
