export const PROSPECT_STATUSES = {
  ASSESSING: "Assessing",
  DOCUMENTS_NEEDED: "Documents needed"
};

export const DISABLED_STATUSES_FOR_UPLOAD_DOCUMENTS = [
  PROSPECT_STATUSES.ASSESSING,
  PROSPECT_STATUSES.DOCUMENTS_NEEDED
];
