import { PROSPECT_STATUSES } from "../../constants/index";

export const DISABLED_STATUSES_FOR_UPLOAD_DOCUMENTS = [
  PROSPECT_STATUSES.ASSESSING,
  PROSPECT_STATUSES.DOCUMENTS_NEEDED,
  PROSPECT_STATUSES.NEED_ADDITIONAL_INFORMATION_DOCUMENTS
];
