export const PROSPECT_STATUSES = {
  ASSESSING: "Assessing",
  DOCUMENTS_NEEDED: "Documents needed",
  NEED_ADDITIONAL_INFORMATION_DOCUMENTS: "Need Additional Information/Documents"
};

export const DISABLED_STATUSES_FOR_UPLOAD_DOCUMENTS = [
  PROSPECT_STATUSES.ASSESSING,
  PROSPECT_STATUSES.DOCUMENTS_NEEDED,
  PROSPECT_STATUSES.NEED_ADDITIONAL_INFORMATION_DOCUMENTS
];
