export const listOfWordsToBeShortened = {
  trading: "TRDG",
  company: "CO",
  "free zone": "FZ",
  branch: "BR",
  retail: "RTL",
  packaging: "PKGNG",
  industrial: "INDL",
  transport: "TRANS",
  transportation: "TRANS",
  equipment: "EQPT",
  maintenance: "MNT",
  institution: "INSTN",
  electromechanical: "ELCTML",
  technical: "TECH",
  repair: "RPR",
  repairing: "RPRG",
  "sole proprietorship": "SP",
  general: "GEN",
  construction: "CNSTR",
  management: "MGMT",
  international: "INTL",
  garments: "GRMT",
  installation: "INSTL",
  service: "SVC",
  services: "SVCS",
  building: "BLDG",
  material: "MTL",
  Materials: "MTLS",
  limited: "LTD",
  machinery: "MCH",
  development: "DVP",
  "abu dhabi": "AUH",
  export: "XPRT",
  contracting: "CONT",
  communication: "COMM",
  mechanical: "MCHL",
  heavy: "HVY",
  light: "LT",
  vehicle: "VCL",
  vehicles: "VCL",
  trucks: "TRKS",
  aluminium: "ALMNM",
  foodstuff: "FDSTF"
};
