# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- develop

#pool:
  #vmImage: 'Ubuntu-16.04'

variables:
- group: skiply
- name: imageName
  value: 'skiply_base_lib'


jobs:  
- job:  OpenSourceJDK_Build
  pool:
    vmImage: 'Ubuntu-16.04'
  condition: eq(variables['Build.SourceBranchName'], 'develop')
  displayName: Skiply base image based on OpenSource JDK
  steps:
    - script: |
        docker login -u $(acr_repo_name) -p $(acr_repo_password) $(acr_repo_name).azurecr.io
        docker build -f Dockerfile --target skiply-base-lib -t $(acr_repo_name).azurecr.io/$(imageName):latest .
        docker push $(acr_repo_name).azurecr.io/$(imageName):latest

- job: AWSLinuxBased_Build
  pool:
    vmImage: 'Ubuntu-16.04'
  condition: eq(variables['Build.SourceBranchName'], 'develop')
  displayName: Skiply base image based on Amazon Linux
  steps:
    - script: |
        docker login -u $(acr_repo_name) -p $(acr_repo_password) $(acr_repo_name).azurecr.io
        docker build -f Dockerfile_aws --target skiply-awsbase-lib -t $(acr_repo_name).azurecr.io/$(imageName):aws_latest .
        docker push $(acr_repo_name).azurecr.io/$(imageName):aws_latest

